Add `mutateImage: false` policy option
IBM/portieris pull request #251
Opened 2021-02-01 14:42 UTC by sjhx

Signed-off-by: Stuart Hayton <stuart.hayton@uk.ibm.com>
resoves: https://github.com/IBM/portieris/issues/244

2021-02-01 14:43 UTC, sjhx commented
Will need test and doc work so this is a proposal at this point.

2021-02-09 13:35 UTC, jhart1685 requested changes
Code looks good to me - just a couple of nits in the documentation.

2021-02-09 13:35 UTC, jhart1685 commented on README.md
> +We have found some closed loop deployment technologies verify that the image running is the expected one by looking at the image reference in the running container and seeing a mutated image referenc
`chnage` typo

2021-02-09 13:35 UTC, jhart1685 commented on README.md
> +We strongly recommend that this option is used only where absolutely necessary and not used alongside `trust` requirements since notaryV1 tags are in not directly linked to registry tags and thus une
`tags are in not directly` ?

2021-02-09 13:42 UTC, jhart1685 approved these changes
looks good to me

2021-02-09 13:43 UTC, merged